//
// This code was generated by a tool.
//
//
//   bebopc version:
//       3.2.3
//
//
//   bebopc source:
//       https://github.com/6over3/bebop
//
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//

#![allow(warnings)]

use bebop::FixedSized as _;
use core::convert::TryInto as _;
use std::io::Write as _;

#[derive(Clone, Debug, PartialEq)]
pub struct KeyValue<'raw> {
    pub key: &'raw str,
    pub value: i64,
}

impl<'raw> ::bebop::SubRecord<'raw> for KeyValue<'raw> {
    const MIN_SERIALIZED_SIZE: usize =
        <&'raw str>::MIN_SERIALIZED_SIZE + <i64>::MIN_SERIALIZED_SIZE;

    #[inline]
    fn serialized_size(&self) -> usize {
        self.key.serialized_size() + self.value.serialized_size()
    }

    ::bebop::define_serialize_chained!(Self => |zelf, dest| {
        Ok(
            zelf.key._serialize_chained(dest)? +
            zelf.value._serialize_chained(dest)?
        )
    });

    fn _deserialize_chained(raw: &'raw [u8]) -> ::bebop::DeResult<(usize, Self)> {
        let mut i = 0;
        if raw.len() - i < Self::MIN_SERIALIZED_SIZE {
            let missing = Self::MIN_SERIALIZED_SIZE - (raw.len() - i);
            return Err(::bebop::DeserializeError::MoreDataExpected(missing));
        }

        let (read, v0) = ::bebop::SubRecord::_deserialize_chained(&raw[i..])?;
        i += read;
        let (read, v1) = ::bebop::SubRecord::_deserialize_chained(&raw[i..])?;
        i += read;

        Ok((i, Self { key: v0, value: v1 }))
    }
}

impl<'raw> ::bebop::Record<'raw> for KeyValue<'raw> {}

#[derive(Clone, Debug, PartialEq, Default)]
pub struct GameMessage<'raw> {
    /// Field 1
    pub updates: ::core::option::Option<::std::vec::Vec<KeyValue<'raw>>>,
    /// Field 2
    pub clicks: ::core::option::Option<::std::vec::Vec<KeyValue<'raw>>>,
    /// Field 3
    pub clear: ::core::option::Option<bool>,
}

impl<'raw> ::bebop::SubRecord<'raw> for GameMessage<'raw> {
    const MIN_SERIALIZED_SIZE: usize = ::bebop::LEN_SIZE + 1;

    #[inline]
    fn serialized_size(&self) -> usize {
        ::bebop::LEN_SIZE
            + 1
            + self
                .updates
                .as_ref()
                .map(|v| v.serialized_size() + 1)
                .unwrap_or(0)
            + self
                .clicks
                .as_ref()
                .map(|v| v.serialized_size() + 1)
                .unwrap_or(0)
            + self
                .clear
                .as_ref()
                .map(|v| v.serialized_size() + 1)
                .unwrap_or(0)
    }

    ::bebop::define_serialize_chained!(Self => |zelf, dest| {
        let size = zelf.serialized_size();
        ::bebop::write_len(dest, size - ::bebop::LEN_SIZE)?;
        if let Some(ref v) = zelf.updates {
            1u8._serialize_chained(dest)?;
            v._serialize_chained(dest)?;
        }
        if let Some(ref v) = zelf.clicks {
            2u8._serialize_chained(dest)?;
            v._serialize_chained(dest)?;
        }
        if let Some(ref v) = zelf.clear {
            3u8._serialize_chained(dest)?;
            v._serialize_chained(dest)?;
        }
        0u8._serialize_chained(dest)?;
        Ok(size)
    });

    fn _deserialize_chained(raw: &'raw [u8]) -> ::bebop::DeResult<(usize, Self)> {
        let mut i = 0;
        let len = ::bebop::read_len(&raw[i..])? + ::bebop::LEN_SIZE;
        i += ::bebop::LEN_SIZE;

        #[cfg(not(feature = "unchecked"))]
        if len == 0 {
            return Err(::bebop::DeserializeError::CorruptFrame);
        }

        if raw.len() < len {
            return Err(::bebop::DeserializeError::MoreDataExpected(len - raw.len()));
        }

        let mut _updates = None;
        let mut _clicks = None;
        let mut _clear = None;

        #[cfg(not(feature = "unchecked"))]
        let mut last = 0;

        while i < len {
            let di = raw[i];

            #[cfg(not(feature = "unchecked"))]
            if di != 0 {
                if di < last {
                    return Err(::bebop::DeserializeError::CorruptFrame);
                }
                last = di;
            }

            i += 1;
            match di {
                0 => {
                    break;
                }
                1 => {
                    #[cfg(not(feature = "unchecked"))]
                    if _updates.is_some() {
                        return Err(::bebop::DeserializeError::DuplicateMessageField);
                    }
                    let (read, value) = ::bebop::SubRecord::_deserialize_chained(&raw[i..])?;
                    i += read;
                    _updates = Some(value)
                }
                2 => {
                    #[cfg(not(feature = "unchecked"))]
                    if _clicks.is_some() {
                        return Err(::bebop::DeserializeError::DuplicateMessageField);
                    }
                    let (read, value) = ::bebop::SubRecord::_deserialize_chained(&raw[i..])?;
                    i += read;
                    _clicks = Some(value)
                }
                3 => {
                    #[cfg(not(feature = "unchecked"))]
                    if _clear.is_some() {
                        return Err(::bebop::DeserializeError::DuplicateMessageField);
                    }
                    let (read, value) = ::bebop::SubRecord::_deserialize_chained(&raw[i..])?;
                    i += read;
                    _clear = Some(value)
                }
                _ => {
                    i = len;
                    break;
                }
            }
        }

        if i != len {
            debug_assert!(i > len);
            return Err(::bebop::DeserializeError::CorruptFrame);
        }

        Ok((
            i,
            Self {
                updates: _updates,
                clicks: _clicks,
                clear: _clear,
            },
        ))
    }
}

impl<'raw> ::bebop::Record<'raw> for GameMessage<'raw> {}

#[cfg(feature = "bebop-owned-all")]
pub mod owned {
    #![allow(warnings)]

    use bebop::FixedSized as _;
    use core::convert::TryInto as _;
    use std::io::Write as _;

    #[derive(Clone, Debug, PartialEq)]
    pub struct KeyValue {
        pub key: String,
        pub value: i64,
    }

    impl<'raw> ::core::convert::From<super::KeyValue<'raw>> for KeyValue {
        fn from(value: super::KeyValue) -> Self {
            Self {
                key: value.key.into(),
                value: value.value,
            }
        }
    }

    impl<'raw> ::bebop::SubRecord<'raw> for KeyValue {
        const MIN_SERIALIZED_SIZE: usize =
            <String>::MIN_SERIALIZED_SIZE + <i64>::MIN_SERIALIZED_SIZE;

        #[inline]
        fn serialized_size(&self) -> usize {
            self.key.serialized_size() + self.value.serialized_size()
        }

        ::bebop::define_serialize_chained!(Self => |zelf, dest| {
            Ok(
                zelf.key._serialize_chained(dest)? +
                zelf.value._serialize_chained(dest)?
            )
        });

        fn _deserialize_chained(raw: &'raw [u8]) -> ::bebop::DeResult<(usize, Self)> {
            let mut i = 0;
            if raw.len() - i < Self::MIN_SERIALIZED_SIZE {
                let missing = Self::MIN_SERIALIZED_SIZE - (raw.len() - i);
                return Err(::bebop::DeserializeError::MoreDataExpected(missing));
            }

            let (read, v0) = ::bebop::SubRecord::_deserialize_chained(&raw[i..])?;
            i += read;
            let (read, v1) = ::bebop::SubRecord::_deserialize_chained(&raw[i..])?;
            i += read;

            Ok((i, Self { key: v0, value: v1 }))
        }
    }

    impl<'raw> ::bebop::Record<'raw> for KeyValue {}

    #[derive(Clone, Debug, PartialEq, Default)]
    pub struct GameMessage {
        /// Field 1
        pub updates: ::core::option::Option<::std::vec::Vec<KeyValue>>,
        /// Field 2
        pub clicks: ::core::option::Option<::std::vec::Vec<KeyValue>>,
        /// Field 3
        pub clear: ::core::option::Option<bool>,
    }

    impl<'raw> ::core::convert::From<super::GameMessage<'raw>> for GameMessage {
        fn from(value: super::GameMessage) -> Self {
            Self {
                updates: value
                    .updates
                    .map(|value| value.into_iter().map(|value| value.into()).collect()),
                clicks: value
                    .clicks
                    .map(|value| value.into_iter().map(|value| value.into()).collect()),
                clear: value.clear,
            }
        }
    }

    impl<'raw> ::bebop::SubRecord<'raw> for GameMessage {
        const MIN_SERIALIZED_SIZE: usize = ::bebop::LEN_SIZE + 1;

        #[inline]
        fn serialized_size(&self) -> usize {
            ::bebop::LEN_SIZE
                + 1
                + self
                    .updates
                    .as_ref()
                    .map(|v| v.serialized_size() + 1)
                    .unwrap_or(0)
                + self
                    .clicks
                    .as_ref()
                    .map(|v| v.serialized_size() + 1)
                    .unwrap_or(0)
                + self
                    .clear
                    .as_ref()
                    .map(|v| v.serialized_size() + 1)
                    .unwrap_or(0)
        }

        ::bebop::define_serialize_chained!(Self => |zelf, dest| {
            let size = zelf.serialized_size();
            ::bebop::write_len(dest, size - ::bebop::LEN_SIZE)?;
            if let Some(ref v) = zelf.updates {
                1u8._serialize_chained(dest)?;
                v._serialize_chained(dest)?;
            }
            if let Some(ref v) = zelf.clicks {
                2u8._serialize_chained(dest)?;
                v._serialize_chained(dest)?;
            }
            if let Some(ref v) = zelf.clear {
                3u8._serialize_chained(dest)?;
                v._serialize_chained(dest)?;
            }
            0u8._serialize_chained(dest)?;
            Ok(size)
        });

        fn _deserialize_chained(raw: &'raw [u8]) -> ::bebop::DeResult<(usize, Self)> {
            let mut i = 0;
            let len = ::bebop::read_len(&raw[i..])? + ::bebop::LEN_SIZE;
            i += ::bebop::LEN_SIZE;

            #[cfg(not(feature = "unchecked"))]
            if len == 0 {
                return Err(::bebop::DeserializeError::CorruptFrame);
            }

            if raw.len() < len {
                return Err(::bebop::DeserializeError::MoreDataExpected(len - raw.len()));
            }

            let mut _updates = None;
            let mut _clicks = None;
            let mut _clear = None;

            #[cfg(not(feature = "unchecked"))]
            let mut last = 0;

            while i < len {
                let di = raw[i];

                #[cfg(not(feature = "unchecked"))]
                if di != 0 {
                    if di < last {
                        return Err(::bebop::DeserializeError::CorruptFrame);
                    }
                    last = di;
                }

                i += 1;
                match di {
                    0 => {
                        break;
                    }
                    1 => {
                        #[cfg(not(feature = "unchecked"))]
                        if _updates.is_some() {
                            return Err(::bebop::DeserializeError::DuplicateMessageField);
                        }
                        let (read, value) = ::bebop::SubRecord::_deserialize_chained(&raw[i..])?;
                        i += read;
                        _updates = Some(value)
                    }
                    2 => {
                        #[cfg(not(feature = "unchecked"))]
                        if _clicks.is_some() {
                            return Err(::bebop::DeserializeError::DuplicateMessageField);
                        }
                        let (read, value) = ::bebop::SubRecord::_deserialize_chained(&raw[i..])?;
                        i += read;
                        _clicks = Some(value)
                    }
                    3 => {
                        #[cfg(not(feature = "unchecked"))]
                        if _clear.is_some() {
                            return Err(::bebop::DeserializeError::DuplicateMessageField);
                        }
                        let (read, value) = ::bebop::SubRecord::_deserialize_chained(&raw[i..])?;
                        i += read;
                        _clear = Some(value)
                    }
                    _ => {
                        i = len;
                        break;
                    }
                }
            }

            if i != len {
                debug_assert!(i > len);
                return Err(::bebop::DeserializeError::CorruptFrame);
            }

            Ok((
                i,
                Self {
                    updates: _updates,
                    clicks: _clicks,
                    clear: _clear,
                },
            ))
        }
    }

    impl<'raw> ::bebop::Record<'raw> for GameMessage {}
}
