name: Docker

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  push:
    branches: [ "master" ]
    # Publish semver tags as releases.
    tags: [ "v*.*.*" ]
  pull_request:
    branches: [ "master" ]

concurrency:
  group: ${{ github.workflow }}

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  REPO_NAME: ${{ github.repository }}

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
            path: main

      # Install the cosign tool except on PR
      # https://github.com/sigstore/cosign-installer
      - name: Install cosign
        if: github.event_name != 'pull_request'
        uses: sigstore/cosign-installer@59acb6260d9c0ba8f4a2f9d9b48431a222b68e20 #v3.5.0
        with:
          cosign-release: "v2.2.4"

      - name: Set up Depot
        uses: depot/setup-action@v1 # v3.0.0

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata for redis-game image
        id: meta-redis-game
        uses: docker/metadata-action@96383f45573cb7f253c731d3b3ab81c87ef81934 # v5.0.0
        with:
          bake-target: docker-metadata-action-redis-game
          images: |
            ${{ env.REGISTRY }}/${{ env.REPO_NAME }}/redis-game

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/bake-action
      - name: Build and push Docker image
        id: build-and-push
        uses: depot/bake-action@v1
        with:
          workdir: main
          files: |
            ./docker-bake.hcl
            cwd://${{ steps.meta-redis-game.outputs.bake-file }}
          push: ${{ github.event_name != 'pull_request' }}
          project: fqf69bcncm
          targets: default

      # Sign the resulting Docker image digest except on PRs.
      # This will only write to the public Rekor transparency log when the Docker
      # repository is public to avoid leaking data.  If you would like to publish
      # transparency data even for private images, pass --force to cosign below.
      # https://github.com/sigstore/cosign
      - name: Sign the published Docker image
        if: ${{ github.event_name != 'pull_request' }}
        env:
          METADATA: ${{ steps.build-and-push.outputs.metadata }}
        run: |
          # Use jq to extract every tag and its corresponding digest from the metadata JSON
          echo "${METADATA}" | jq -r 'to_entries[] | .value["containerimage.digest"] as $digest | (.value["image.name"] | split(","))[] | . + "@" + $digest' | while read -r image_with_digest; do
            echo "Signing ${image_with_digest}..."
            cosign sign --yes "${image_with_digest}"
          done
